### ISSUE TITLE
Summary Statistics Helper Function for `ChoiceDataset` Class

### ISSUE THREAD

**Issue by TianyuDu** [gsbDBI/torch-choice#7]

**Comment by TianyuDu** [comment]
I am currently working on this on the `dataset-summary-method` branch [here](https://github.com/gsbDBI/torch-choice/tree/dataset-summary-method).

**Comment by TianyuDu** [comment]
I have created a pull request [here](https://github.com/gsbDBI/torch-choice/pull/11) implementing the `summary()` feature.

Here is an example output from the `summary()` method:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/22979098/187048067-ad4232f5-9418-42e6-bca7-f723fd5fb3d1.png">

@kanodiaayush Could you please review the pull request a bit and let me know if you have any comments? I will merge the branch after the weekend.

**Comment by kanodiaayush** [comment]
I like this. I imagine after some people (or we ourselves) use it a bit we will have feedback points on this. I am approving the pull request. I took a look at the code and it looks good to me.

Thanks for adding this. This is a good one.

**Comment by TianyuDu** [comment]
Merged.
